services:
  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    # May not publish ports in some environments
    ports:
      - "3310:3310"
    # Use a volume to persist ClamAV database
#    volumes:
#      - ./clamav:/var/lib/clamav
    healthcheck:
      test: ["CMD", "clamdscan", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  clamav-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clamav-api
    ports:
      - "8080:8080"
    volumes:
      - ./configs/config.yaml:/etc/clamav-api/config.yaml:ro
    environment:
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
      - WEBHOOK_URL=http://webhook:8080
    depends_on:
      clamav:
        condition: service_healthy
    restart: unless-stopped

  webhook:
    image: mendhak/http-https-echo:latest
    container_name: webhook
    ports:
      - "8081:8080"
    restart: unless-stopped
