{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "clamav.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}