apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav-api
  namespace: antivirus
  labels:
    app: clamav-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clamav-api
  template:
    metadata:
      labels:
        app: clamav-api
    spec:
      containers:
        - name: clamav-api
          image: aleskapot/clamav-api:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: clamav-api-auth
                  key: AUTH_API_KEY
            - name: CLAMAV_HOST
              valueFrom:
                configMapKeyRef:
                  name: clamav-api-cm
                  key: CLAMAV_HOST
            - name: CLAMAV_PORT
              valueFrom:
                configMapKeyRef:
                  name: clamav-api-cm
                  key: CLAMAV_PORT
            - name: WEBHOOK_URL
              valueFrom:
                configMapKeyRef:
                  name: clamav-api-cm
                  key: WEBHOOK_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10